/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/forrrest.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forrrest.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.504, -0.171, 0.206]} scale={0.039}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials['HOJAS.005']} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials['HOJAS.005']} />
          <mesh geometry={nodes.Mesh_10.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_11.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_12.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_13.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_14.geometry} material={materials['LEAVES.002']} />
          <mesh geometry={nodes.Mesh_15.geometry} material={materials['LEAVES.002']} />
          <mesh geometry={nodes.Mesh_16.geometry} material={materials['VEIN.001']} />
          <mesh geometry={nodes.Mesh_17.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Mesh_2.geometry} material={materials['HOJAS.005']} />
          <mesh geometry={nodes.Mesh_3.geometry} material={materials['HOJAS.005']} />
          <mesh geometry={nodes.Mesh_4.geometry} material={materials.GLOW} />
          <mesh geometry={nodes.Mesh_5.geometry} material={materials.GLOW} />
          <mesh geometry={nodes.Mesh_6.geometry} material={materials['Material.019']} />
          <mesh geometry={nodes.Mesh_7.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_8.geometry} material={materials['LEAVES.003']} />
          <mesh geometry={nodes.Mesh_9.geometry} material={materials['LEAVES.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/forrrest.glb')
